CITRON_EXT_PATH = (nil)(())
sum: helloworldTrueNil6661
Uncaught error has occurred.
Cast of type Nil to type Number failed: Cast of type Boolean to type Number failed: Cast of type String to type Number failed: Cast of type String to type Number failed: cannot build number, extra characters in string
#3 min (tests/test0173.ctr: 13)
#2 + (tests/test0173.ctr: 13)
#1 write: (tests/test0173.ctr: 13)
------------------------------------
The probable cause of the exception: 
11 | 
12 | Pen write: ( 'sum: ' + ( a sum ) ), brk.
13 | Pen write: ( 'min: ' + ( a min ) ), brk.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
14 | Pen write: ( 'max: ' + ( a max ) ), brk.
