Break for-loop, 0-4.
iteration #0
iteration #1
iteration #2
iteration #3
iteration #4
Break while-true loop, 0-4.
iteration #0
iteration #1
iteration #2
iteration #3
iteration #4
Break while-false loop, 5,4.
iteration #5
iteration #4
Break times loop, 1-4.
iteration #0
iteration #1
iteration #2
iteration #3
iteration #4
Test Array each-loop: 0,1
iteration #0
iteration #1
Test Map each-loop: c only
iterationthirdc
Test HashMap each-loop
some element in hm
some element in hm
some element in hm
