CITRON_EXT_PATH = (nil)(())
I am the Child process
Child received: hello
Child received: world
Child received: stop
Child sleeps 4 sec, wait for it...
Uncaught error has occurred.
json error on line 1: '[' or '{' expected near '2e9'
#5 parse:genericType: (tests/test0255.ctr: 15)
#4 wait: (tests/test0255.ctr: 15)
#3 whileTrue: (tests/test0255.ctr: 5)
#2 new: (tests/test0255.ctr: 3)
#1 q (tests/test0255.ctr: 3)
------------------------------------
The probable cause of the exception: 
13 | 
14 | 	Pen write: 'Child sleeps 4 sec, wait for it...', brk.
15 | 	Clock wait: (JSON parse: '2e9' genericType: Object).
~~~~~~~~~~~~~~~~~~~~~~~~~~~^
16 | 	Pen write: 1, brk.

CITRON_EXT_PATH = (nil)(())
I am Parent Process
Parent received: thanks for hello
Parent received: thanks for world
Parent received: thanks for stop
Joined processes
Parent is Done
