Uncaught error has occurred.
Key not found: a
#6 a (tests/test0287.ctr: 5)
#5 letEqualAst:in: (<eval>: 2)
#4 fmap: (<eval>: 2)
#3 toArray (tests/test0287.ctr: 6)
#2 writeln: (tests/test0287.ctr: 6)
#1 Library/Data/Generator (tests/test0287.ctr: 1)
------------------------------------
The probable cause of the exception: 
3 | 
4 | var g is Generator elementsOf: 'test1234' reverse.
5 | f is [a + b,, (a: f), (b: g),, (a !=: b), ('13s' contains: b, not)].
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
6 | Pen writeln: f toArray.
