CITRON_EXT_PATH = (nil)(())
Continue for-loop, No - before 6 and up.
1
-2
-3
-4
-5
6
7
8
9
10

Continue while-true, No --> before 5 and up.
iteration #0
-->iteration #1
-->iteration #2
-->iteration #3
-->iteration #4
iteration #5
iteration #6
iteration #7
iteration #8
iteration #9

Continue while-false, No - before 3 only.
iteration #10
-iteration #9
-iteration #8
-iteration #7
-iteration #6
-iteration #5
-iteration #4
iteration #3
-iteration #2
-iteration #1
-
Continue times-loop, No ||| before 3.
iteration #0
|||iteration #1
|||iteration #2
iteration #3
|||iteration #4
|||
Uncaught error has occurred.
#16 continue (tests/test0113.ctr: 43)
#15 run (tests/test0113.ctr: 43)
#14 times: (tests/test0113.ctr: 34)
#13 whileFalse: (tests/test0113.ctr: 24)
#12 continue (tests/test0113.ctr: 17)
#11 continue (tests/test0113.ctr: 17)
#10 continue (tests/test0113.ctr: 17)
#9 continue (tests/test0113.ctr: 17)
#8 continue (tests/test0113.ctr: 17)
#7 whileTrue: (tests/test0113.ctr: 14)
#6 continue (tests/test0113.ctr: 5)
#5 continue (tests/test0113.ctr: 5)
#4 continue (tests/test0113.ctr: 5)
#3 continue (tests/test0113.ctr: 5)
#2 continue (tests/test0113.ctr: 5)
#1 to:step:do: (tests/test0113.ctr: 3)
------------------------------------
The probable cause of the exception: 
41 | 
42 | #nothing should happen, no error
43 | { True continue. Pen write: 'dont write this!', brk. } run.
~~~~~~~~~~~~~~~~~~^
