Break for-loop, 0-4.
iteration #0
iteration #1
iteration #2
iteration #3
iteration #4
Break while-true loop, 0-4.
iteration #0
iteration #1
iteration #2
iteration #3
iteration #4
Break while-false loop, 5,4.
iteration #5
iteration #4
Break times loop, 1-4.
iteration #0
iteration #1
iteration #2
iteration #3
iteration #4
Break block, dont print line.
Uncaught error has occurred.
#6 break (tests/test0107.ctr: 37)
#5 run (tests/test0107.ctr: 37)
#4 times: (tests/test0107.ctr: 30)
#3 whileFalse: (tests/test0107.ctr: 22)
#2 whileTrue: (tests/test0107.ctr: 14)
#1 to:step:do: (tests/test0107.ctr: 4)
------------------------------------
The probable cause of the exception: 
35 | 
36 | Pen write: 'Break block, dont print line.', brk.
37 | { True break. Pen write: 'dont write this!', brk. } run.
~~~~~~~~~~~~~~~^
