Array ← [4, 13] ; [3, 10] ; [2, 7] ; [1, 4] ; [0, 1] ; [1] ; [2] ; [3]
[([FilteredGenerator<[StepGenerator]>]), ([MappedGenerator<[StepGenerator]>])]
Array ← 't4' ; 't2' ; 'tt' ; 'te' ; 'tt' ; 'e4' ; 'e2' ; 'et' ; 'ee' ; 'et' ; 's4' ; 's2' ; 'st' ; 'se' ; 'st' ; 't4' ; 't2' ; 'tt' ; 'te' ; 'tt' ; '14' ; '12' ; '1t' ; '1e' ; '1t' ; '24' ; '22' ; '2t' ; '2e' ; '2t' ; '34' ; '32' ; '3t' ; '3e' ; '3t' ; '44' ; '42' ; '4t' ; '4e' ; '4t'
