all:
	cd $(realpath .)/.. && ./make-lambdaf.sh fast

clean:
	cd $(realpath .)/.. && ./make-lambdaf.sh clean

install:
	echo "Hello!"

uninstall:
	echo "Noooooooooooooooooooooooooooooooo!"

distclean:
	echo "ok"
