<?xml  version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN"   "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0" >
<!-- Generated via Iro -->
<dict>
  <key>fileTypes</key>
  <array>
    <string>ctr</string>
   </array>
  <key>name</key>
  <string>Citron</string>
  <key>patterns</key>
  <array>
    <dict>
      <key>include</key>
      <string>#main</string>
    </dict>
   </array>
  <key>scopeName</key>
  <string>source.Citron</string>
  <key>uuid</key>
  <string></string>
  <key>repository</key>
  <dict>
    <key>main</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>begin</key>
          <string>(?:(@comptime)\b)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>markup.deleted.Citron</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>entity.name.Citron</string>
          <key>end</key>
          <string>(\s*)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.Citron</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>\b(var|my|const|frozen)\b</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.other.unit.Citron</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>variable.Citron</string>
          <key>end</key>
          <string>(?:(&amp;&amp;|&amp;)?([^\s\d\x{003a}.\x{002c}\[\]\(\)\{\}\#][^\s\x{003a}.\x{002c}\[\]\(\)\{\}\#]*))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>constant.character.escape.Citron</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>variable.Citron</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(?:(pure)(\s*\{))</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.other.unit.Citron</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>entity.name.Citron</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#main__3</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\})</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.Citron</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(\$[\x{0021}\x{002c}\x{0027}\x{0060}](?!=\s))</string>
          <key>name</key>
          <string>constant.character.escape.Citron</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\$(?=\())</string>
          <key>name</key>
          <string>constant.character.escape.Citron</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([\[\]\(\)\^\}])</string>
          <key>name</key>
          <string>entity.name.Citron</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(?:(\s*)(\bis\b|\:\=|\=\&gt;)(\s*))</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>text.Citron</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>keyword.control.Citron</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>text.Citron</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(?:(\?&gt;))</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.regexp.Citron</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#main__4</string>
            </dict>
           </array>
          <key>end</key>
          <string>(&lt;\?)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.regexp.Citron</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(0[xX][0-9a-fA-F]+|0[cC][0-7]+|0[bB][01]+|\d+\.\d+|\d+)</string>
          <key>name</key>
          <string>constant.numeric.Citron</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(&apos;)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.Citron</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#string</string>
            </dict>
           </array>
          <key>end</key>
          <string>((?!&lt;\\)&apos;)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.Citron</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(?:(\\)((?:(?:\:[^\s\d\x{003a}.\x{002c}\[\]\(\)\{\}\#][^\s\x{003a}.\x{002c}\[\]\(\)\{\}\#]*\s*)|(?:\:\(.*\)))+))</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.control.Citron</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>keyword.other.unit.Citron</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>text.Citron</string>
          <key>end</key>
          <string>(\s*?)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.Citron</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(?:(\{)(asm)(\s*(?:\:)\s*(?:\w+))*(\s*(?:intel|att|at\&amp;t))?(\s*\(.*\)\s*))</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.Citron</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>markup.deleted.Citron</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>keyword.other.unit.Citron</string>
            </dict>
            <key>4</key>
            <dict>
              <key>name</key>
              <string>markup.deleted.Citron</string>
            </dict>
            <key>5</key>
            <dict>
              <key>name</key>
              <string>markup.deleted.Citron</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#main__6</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\})</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.Citron</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(?:(\{)((?:\s*\:(?:(?:[^\s\d\x{003a}.\x{002c}\[\]\(\)\{\}\#][^\s\x{003a}.\x{002c}\[\]\(\)\{\}\#]*)|(?:\(.*\))))*))</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.Citron</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>keyword.other.unit.Citron</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>entity.name.Citron</string>
          <key>end</key>
          <string>(\s*)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.Citron</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(?:(\#:))</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.Citron</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>markup.deleted.Citron</string>
          <key>end</key>
          <string>(?:(?:(declare)(\s+)(infixr|infixl|lazyev)(\s*)(.*))|(?:(language)(\s+)(.*))$)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>markup.deleted.Citron</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>entity.name.Citron</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>string.regexp.Citron</string>
            </dict>
            <key>4</key>
            <dict>
              <key>name</key>
              <string>entity.name.Citron</string>
            </dict>
            <key>5</key>
            <dict>
              <key>name</key>
              <string>entity.name.function.Citron</string>
            </dict>
            <key>6</key>
            <dict>
              <key>name</key>
              <string>markup.deleted.Citron</string>
            </dict>
            <key>7</key>
            <dict>
              <key>name</key>
              <string>entity.name.Citron</string>
            </dict>
            <key>8</key>
            <dict>
              <key>name</key>
              <string>string.regexp.Citron</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(\#.*$)</string>
          <key>name</key>
          <string>comment.Citron</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>((?:[^\s\d\x{003a}.\x{002c}\[\]\(\)\{\}\#][^\s\x{003a}.\x{002c}\[\]\(\)\{\}\#]*)\:)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.function.Citron</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>entity.name.Citron</string>
          <key>end</key>
          <string>(\s*)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.Citron</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\\)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>constant.character.escape.Citron</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>keyword.control.Citron</string>
          <key>end</key>
          <string>(?:([^\x{003a}]\w*)|(\:(?:[^\s\d\x{003a}.\x{002c}\[\]\(\)\{\}\#][^\s\x{003a}.\x{002c}\[\]\(\)\{\}\#]*)))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>constant.character.escape.Citron</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>keyword.control.Citron</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(?:(\s+)([^\s\d\x{003a}.\x{002c}\[\]\(\)\{\}\#]|[-\x{002b}\x{002a}\x{0026}\x{0025}\x{0024}\x{0040}\x{0021}\x{003d}\x{0022}\x{003b}\x{002f}\x{005c}\x{003c}\x{003e}\x{003f}\x{007e}]+)(\s+))</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.Citron</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>entity.name.function.Citron</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>entity.name.Citron</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>entity.name.Citron</string>
          <key>end</key>
          <string>(\s*)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.Citron</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(?:(\`)([^\s\d\x{003a}.\x{002c}\[\]\(\)\{\}\#][^\s\x{003a}.\x{002c}\[\]\(\)\{\}\#]*)(\1))</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>constant.character.escape.Citron</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>entity.name.type.Citron</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>constant.character.escape.Citron</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>entity.name.Citron</string>
          <key>end</key>
          <string>(\s*?)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.Citron</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(?:(\`?)([^\s\d\x{003a}.\x{002c}\[\]\(\)\{\}\#][^\s\x{003a}.\x{002c}\[\]\(\)\{\}\#]*)(\1))</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>constant.character.escape.Citron</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>text.Citron</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>constant.character.escape.Citron</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>entity.name.Citron</string>
          <key>end</key>
          <string>(\s*?)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.Citron</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>asm</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>(.*)</string>
          <key>name</key>
          <string>comment.Citron</string>
        </dict>
       </array>
    </dict>
    <key>expr_interpolation</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>begin</key>
          <string>\b(var|my|const|frozen)\b</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.other.unit.Citron</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>variable.Citron</string>
          <key>end</key>
          <string>([^\s\d\x{003a}.\x{002c}\[\]\(\)\{\}\#][^\s\x{003a}.\x{002c}\[\]\(\)\{\}\#]*)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>variable.Citron</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(?:(pure)(\s*\{))</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.other.unit.Citron</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>entity.name.Citron</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#expr_interpolation__2</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\})</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.Citron</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(\$[\x{0021}\x{002c}\x{0027}\x{0060}](?!=\s))</string>
          <key>name</key>
          <string>constant.character.escape.Citron</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\$(?=\())</string>
          <key>name</key>
          <string>constant.character.escape.Citron</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([\[\]\(\)\^\}])</string>
          <key>name</key>
          <string>entity.name.Citron</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(?:(\s*)(\bis\b|\:\=|\=\&gt;)(\s*))</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>text.Citron</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>keyword.control.Citron</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>text.Citron</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(?:(\?&gt;))</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.regexp.Citron</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#expr_interpolation__3</string>
            </dict>
           </array>
          <key>end</key>
          <string>(&lt;\?)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.regexp.Citron</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(0[xX][0-9a-fA-F]+|0[cC][0-7]+|0[bB][01]+|\d+\.\d+|\d+)</string>
          <key>name</key>
          <string>constant.numeric.Citron</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(&apos;)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.Citron</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#string</string>
            </dict>
           </array>
          <key>end</key>
          <string>((?!&lt;\\)&apos;)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.Citron</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(?:(\\)((?:\:[^\s\d\x{003a}.\x{002c}\[\]\(\)\{\}\#][^\s\x{003a}.\x{002c}\[\]\(\)\{\}\#]*\s*)+))</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.control.Citron</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>keyword.other.unit.Citron</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>text.Citron</string>
          <key>end</key>
          <string>(\s*?)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.Citron</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(?:(\{)(asm)(\s*(?:\:)\s*(?:\w+))*(\s*(?:intel|att|at\&amp;t))?(\s*\(.*\)\s*))</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.Citron</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>markup.deleted.Citron</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>keyword.other.unit.Citron</string>
            </dict>
            <key>4</key>
            <dict>
              <key>name</key>
              <string>markup.deleted.Citron</string>
            </dict>
            <key>5</key>
            <dict>
              <key>name</key>
              <string>markup.deleted.Citron</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#expr_interpolation__5</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\})</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.Citron</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(?:(\{)((?:\s*\:(?:[^\s\d\x{003a}.\x{002c}\[\]\(\)\{\}\#][^\s\x{003a}.\x{002c}\[\]\(\)\{\}\#]*))*))</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.Citron</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>keyword.other.unit.Citron</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>entity.name.Citron</string>
          <key>end</key>
          <string>(\s*)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.Citron</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(?:(\#:))</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.Citron</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>markup.deleted.Citron</string>
          <key>end</key>
          <string>(?:(?:(declare)(\s+)(infixr|infixl|lazyev)(\s*)(.*))|(?:(language)(\s+)(.*))$)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>markup.deleted.Citron</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>entity.name.Citron</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>string.regexp.Citron</string>
            </dict>
            <key>4</key>
            <dict>
              <key>name</key>
              <string>entity.name.Citron</string>
            </dict>
            <key>5</key>
            <dict>
              <key>name</key>
              <string>entity.name.function.Citron</string>
            </dict>
            <key>6</key>
            <dict>
              <key>name</key>
              <string>markup.deleted.Citron</string>
            </dict>
            <key>7</key>
            <dict>
              <key>name</key>
              <string>entity.name.Citron</string>
            </dict>
            <key>8</key>
            <dict>
              <key>name</key>
              <string>string.regexp.Citron</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(\#.*$)</string>
          <key>name</key>
          <string>comment.Citron</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>((?:[^\s\d\x{003a}.\x{002c}\[\]\(\)\{\}\#][^\s\x{003a}.\x{002c}\[\]\(\)\{\}\#]*)\:)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.function.Citron</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>entity.name.Citron</string>
          <key>end</key>
          <string>(\s*)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.Citron</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\\)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>constant.character.escape.Citron</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>keyword.control.Citron</string>
          <key>end</key>
          <string>(?:([^\x{003a}]\w*)|(\:(?:[^\s\d\x{003a}.\x{002c}\[\]\(\)\{\}\#][^\s\x{003a}.\x{002c}\[\]\(\)\{\}\#]*)))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>constant.character.escape.Citron</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>keyword.control.Citron</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(?:(\s+)([^\s\d\x{003a}.\x{002c}\[\]\(\)\{\}\#]|[-\x{002b}\x{002a}\x{0026}\x{0025}\x{0024}\x{0040}\x{0021}\x{003d}\x{0022}\x{003b}\x{002f}\x{005c}\x{003c}\x{003e}\x{003f}\x{007e}]+)(\s+))</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.Citron</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>entity.name.function.Citron</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>entity.name.Citron</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>entity.name.Citron</string>
          <key>end</key>
          <string>(\s*)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.Citron</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(?:(\`)([^\s\d\x{003a}.\x{002c}\[\]\(\)\{\}\#][^\s\x{003a}.\x{002c}\[\]\(\)\{\}\#]*)(\1))</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>constant.character.escape.Citron</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>entity.name.type.Citron</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>constant.character.escape.Citron</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>entity.name.Citron</string>
          <key>end</key>
          <string>(\s*?)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.Citron</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(?:(\`?)([^\s\d\x{003a}.\x{002c}\[\]\(\)\{\}\#][^\s\x{003a}.\x{002c}\[\]\(\)\{\}\#]*)(\1))</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>constant.character.escape.Citron</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>text.Citron</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>constant.character.escape.Citron</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>entity.name.Citron</string>
          <key>end</key>
          <string>(\s*?)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.Citron</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>expr_interpolation__1</key>
    <dict>
      <key>patterns</key>
      <array>
       </array>
    </dict>
    <key>expr_interpolation__10</key>
    <dict>
      <key>patterns</key>
      <array>
       </array>
    </dict>
    <key>expr_interpolation__11</key>
    <dict>
      <key>patterns</key>
      <array>
       </array>
    </dict>
    <key>expr_interpolation__12</key>
    <dict>
      <key>patterns</key>
      <array>
       </array>
    </dict>
    <key>expr_interpolation__2</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>(.)</string>
          <key>name</key>
          <string>text.Citron</string>
        </dict>
       </array>
    </dict>
    <key>expr_interpolation__3</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>(.)</string>
          <key>name</key>
          <string>string.regexp.Citron</string>
        </dict>
       </array>
    </dict>
    <key>expr_interpolation__4</key>
    <dict>
      <key>patterns</key>
      <array>
       </array>
    </dict>
    <key>expr_interpolation__5</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>begin</key>
          <string>(?:\s*)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.Citron</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#asm</string>
            </dict>
           </array>
          <key>end</key>
          <string>(?=\})</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.Citron</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>expr_interpolation__6</key>
    <dict>
      <key>patterns</key>
      <array>
       </array>
    </dict>
    <key>expr_interpolation__7</key>
    <dict>
      <key>patterns</key>
      <array>
       </array>
    </dict>
    <key>expr_interpolation__8</key>
    <dict>
      <key>patterns</key>
      <array>
       </array>
    </dict>
    <key>expr_interpolation__9</key>
    <dict>
      <key>patterns</key>
      <array>
       </array>
    </dict>
    <key>main__1</key>
    <dict>
      <key>patterns</key>
      <array>
       </array>
    </dict>
    <key>main__10</key>
    <dict>
      <key>patterns</key>
      <array>
       </array>
    </dict>
    <key>main__11</key>
    <dict>
      <key>patterns</key>
      <array>
       </array>
    </dict>
    <key>main__12</key>
    <dict>
      <key>patterns</key>
      <array>
       </array>
    </dict>
    <key>main__13</key>
    <dict>
      <key>patterns</key>
      <array>
       </array>
    </dict>
    <key>main__2</key>
    <dict>
      <key>patterns</key>
      <array>
       </array>
    </dict>
    <key>main__3</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>(.)</string>
          <key>name</key>
          <string>text.Citron</string>
        </dict>
       </array>
    </dict>
    <key>main__4</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>(.)</string>
          <key>name</key>
          <string>string.regexp.Citron</string>
        </dict>
       </array>
    </dict>
    <key>main__5</key>
    <dict>
      <key>patterns</key>
      <array>
       </array>
    </dict>
    <key>main__6</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>begin</key>
          <string>(?:\s*)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.Citron</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#asm</string>
            </dict>
           </array>
          <key>end</key>
          <string>(?=\})</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.Citron</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>main__7</key>
    <dict>
      <key>patterns</key>
      <array>
       </array>
    </dict>
    <key>main__8</key>
    <dict>
      <key>patterns</key>
      <array>
       </array>
    </dict>
    <key>main__9</key>
    <dict>
      <key>patterns</key>
      <array>
       </array>
    </dict>
    <key>string</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>(?:(\$\$)(\w+)\b)</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>constant.character.escape.Citron</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>entity.name.function.Citron</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(\\[^xu])</string>
          <key>name</key>
          <string>constant.character.escape.Citron</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(?:(\\[xuXU])([\x{007b}]?)([0-9a-fA-F]+)([\x{007d}]?))</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>constant.character.escape.Citron</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>constant.character.escape.Citron</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>constant.numeric.Citron</string>
            </dict>
            <key>4</key>
            <dict>
              <key>name</key>
              <string>constant.character.escape.Citron</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\$\{\{)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>constant.character.escape.Citron</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#expr_interpolation</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\}\}\$)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>constant.character.escape.Citron</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(.)</string>
          <key>name</key>
          <string>string.Citron</string>
        </dict>
       </array>
    </dict>
  </dict>
</dict>
</plist>
