<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ctr</string>
	</array>
	<key>foldingStartMarker</key>
	<string>\{</string>
	<key>foldingStopMarker</key>
	<string>^\s*\}|^\s\}</string>
	<key>keyEquivalent</key>
	<string>^~S</string>
	<key>name</key>
	<string>Citron</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(var|my|const)\b</string>
			<key>name</key>
			<string>storage.type.$1.citron</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(me)\b</string>
			<key>name</key>
			<string>storage.modifier.$1.citron</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(new)\b</string>
			<key>name</key>
			<string>keyword.control.$1.citron</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(:=|is)\b</string>
			<key>name</key>
			<string>keyword.operator.assignment.citron</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>:\w+</string>
							<key>name</key>
							<string>entity.name.function.block.citron</string>
						</dict>
					</array>
				</dict>
			</dict>
			<key>comment</key>
			<string>Parse the blocks like: { :a :b ...... }</string>
			<key>match</key>
			<string>\{((\s+|:(\*?)\w+)*)</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#numeric</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Fake reserved word -&gt; main Citron messages</string>
			<key>match</key>
			<string>(?&lt;!\.)\b(ensure|resume|retry|signal)\b(?![?!])</string>
			<key>name</key>
			<string>keyword.control.citron</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Fake conditionals. Citron Methods.</string>
			<key>match</key>
			<string>ifTrue:|ifFalse:|whileFalse:|whileTrue:|else:</string>
			<key>name</key>
			<string>keyword.control.conditionals.citron</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\?></string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.citron</string>
				</dict>
			</dict>
			<key>end</key>
			<string><\?</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.citron</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.raw.citron</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(True|False)\b</string>
			<key>name</key>
			<string>constant.language.boolean.citron</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(Nil)\b</string>
			<key>name</key>
			<string>constant.language.nil.citron</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.constant.citron</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>messages/methods</string>
			<key>match</key>
			<string>(?&gt;[a-zA-Z_]\w*(?&gt;[?!])?)(:)(?!:)</string>
			<key>name</key>
			<string>constant.other.messages.citron</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.citron</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.citron</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.citron</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b[A-Z]\w*\b</string>
			<key>name</key>
			<string>variable.other.constant.citron</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>numeric</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?&lt;!\w)[0-9]+\.[0-9]+s[0-9]*</string>
					<key>name</key>
					<string>constant.numeric.float.scaled.citron</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;!\w)[0-9]+\.[0-9]+([edq]-?[0-9]+)?</string>
					<key>name</key>
					<string>constant.numeric.float.citron</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;!\w)-?[0-9]+r[a-zA-Z0-9]+</string>
					<key>name</key>
					<string>constant.numeric.integer.radix.citron</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;!\w)-?[0-9]+([edq]-?[0-9]+)?</string>
					<key>name</key>
					<string>constant.numeric.integer.citron</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.citron</string>
	<key>uuid</key>
	<string>1ED64A34-BCB1-44E1-A0FE-84053003E322</string>
</dict>
</plist>
